#!/usr/bin/env node
'use strict';

// 添加对ts文件的解析
require('../utils/bootstrap-local');

// 检测NodeJs版本.
// const version = process.version.substr(1).split('.');
// if (Number(version[0]) < 10 || (Number(version[0]) === 10 && Number(version[1]) < 9)) {
//   process.stderr.write(
//     '当前Node.js运行版本' + process.version + '不被cli支持。\n' +
//     '建议更新到10.9或者更高版本。'
//   );

//   process.exit(3);
// }

// 入口文件
require('./generate-view.ts');
